### ISSUE TITLE
Update AWS K8s Lab

### ISSUE THREAD

**Issue by robertjahn** [dt-alliances-workshops/learn-site-content#14]
New K8s Operator
* New Operator installation script (from Jay)
* Update guide instructions & screen shots

Provision Cluster
* Breakup Overview & Setup into two labs
* Prereq -- add instructions to install eksctl - https://learn.alliances.dynatracelabs.com/codelabs/aws-lab6/index.html?index=..%2F..aws-immersion-day#2
* Have the default be `ee-default-keypair` for example `eksctl create cluster --with-oidc --ssh-access --version=1.21 --managed --name dynatrace-workshop --tags "Purpose=dynatrace-modernization-workshop" --ssh-public-key ee-default-keypair`

Lab step to enable K8s events
* Add Lab with this app to see events - https://github.com/dt-demos/simple-web-app/tree/master/boom-app
* Figure out if Davis auto-detects or need to configure custom alert

Clean up script
* enable cleanup lab
* add step to run eksctl to delete cluster

**Comment by akirasoft1** [comment]
outdated issue and was resolved a couple times over ;)
